language: node_js
cache:
  directories:
  - node_modules
notifications:
  email: false
node_js:
- '7'
- '6'
branches:
  except:
  - /^v\d+\.\d+\.\d+$/
env:
  global:
    secure: zUVpzlIi7T06D5HUi+zvxivPhv8L0A6yQvEuuPQwL4X3XMX6zzmCi3Oih7B0L2SDX1j4v5JhLw6hqEWNaKW5lj/mNg2p7vEoantfrekPFddIcVEcBRnvxR4U4lLp5cvWevkanWmz66WyvJxPVr0KZUyuA1Yn7wOaukQRNRshz9faWciPb+qmBF6VF51Eb9sV0U5O7HBs54TpvUhESXv1UBzQY+SzP/U4ImKb5Gz4moXeR8PLzmssy9nsfQrUgrEYEbfiWqJ5NIvcG+4NtdjBUCo6Z0OJ+wMra/dYYK4uYQgsO3l26u+sOr2mcRhLDzVrYqi9Z4f/gkMtNUJUFXTshOPoKi5OHlwMNh/q/JEpZrhXkR+NOwNiQiGYLVNLWr3BpYjoD9CtofLkssRSgYevEGHLXIMwbf5GeBZeOPti2+w7loptWKNMtCt/7T5mnl0qH+9V1ToyMG7X0KLmQsFLA+qkjWIi76TfO6eohyTr4dv57l1Fy+ZaW004T66Lx5W9GN+Pt8anO3/Whn7CWf90govjB3WD+eX5lgpKhFUzEADbEEdDCEI5cDHaaag1xyjaq2LiyFepgpGyw6fgw+efKDzdvA3Dr+5YZ7OIt99PqOeeXvv3uHOn53pQsG2bPdAbAPMCdN5eMQyAC2/5MVWZEkYIqOZ0IQVRkn1nzMgCdyU=
